apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jea8uk2x6-java-springboot
  janus-idp.io/tekton: jea8uk2x6-java-springboot
  backstage.io/kubernetes-id: jea8uk2x6-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jea8uk2x6-java-springboot
resources:
- deployment.yaml
- route.yaml
- service.yaml
